import { z } from 'zod';

export const entrySchema = z.object({ id: z.string().min(1).max(80), title: z.string().min(1).max(160), subtitle: z.string().max(200).optional(), period: z.string().max(100).optional(), location: z.string().max(120).optional(), body: z.string().max(3000).optional(), tags: z.array(z.string().max(60)).max(30).optional(), url: z.string().url().optional() });
export const sectionSchema = z.object({ id: z.string().regex(/^[a-z0-9-]+$/), type: z.string().max(40), title: z.string().min(1).max(100), visible: z.boolean(), order: z.number().int().min(0), entries: z.array(entrySchema).max(100) });
export const cvSchema = z.object({ name: z.string().min(1).max(100), role: z.string().min(1).max(160), tagline: z.string().max(500), location: z.string().max(120), availability: z.string().max(160), email: z.string().email(), phone: z.string().max(50).optional(), about: z.string().max(3000), socials: z.array(z.object({ label: z.string().max(60), url: z.string().url() })).max(20), sections: z.array(sectionSchema).max(30), profileImageUrl: z.string().optional(), updatedAt: z.string().optional() });
export const themeSchema = z.object({ background: z.string().regex(/^#[0-9a-f]{6}$/i), surface: z.string().regex(/^#[0-9a-f]{6}$/i), text: z.string().regex(/^#[0-9a-f]{6}$/i), muted: z.string().regex(/^#[0-9a-f]{6}$/i), accent: z.string().regex(/^#[0-9a-f]{6}$/i), accent2: z.string().regex(/^#[0-9a-f]{6}$/i), border: z.string().regex(/^#[0-9a-f]{6}$/i), fontHeading: z.enum(['Manrope','Fraunces','Space Grotesk','DM Sans']), fontBody: z.enum(['DM Sans','Inter','Manrope']), radius: z.number().min(0).max(32), spacing: z.number().min(12).max(36) });
export type CvDocument = z.infer<typeof cvSchema>;
export type Theme = z.infer<typeof themeSchema>;

export const defaultTheme: Theme = { background:'#101612',surface:'#18201a',text:'#f1f4ee',muted:'#aab5aa',accent:'#c6ff4a',accent2:'#74dec7',border:'#344038',fontHeading:'Manrope',fontBody:'DM Sans',radius:18,spacing:24 };
export const defaultCv: CvDocument = { name:'Alex Morgan',role:'Product engineer',tagline:'I turn ambiguous problems into calm, useful digital products — bridging design sensibility with dependable engineering.',location:'Vienna, Austria',availability:'Available for selected collaborations',email:'alex@example.com',about:'I’m a product-minded engineer who cares about the entire experience: the sentence that sets expectations, the interaction that builds confidence, and the system that keeps working after launch.',socials:[{label:'LinkedIn',url:'https://www.linkedin.com'},{label:'GitHub',url:'https://github.com'}],sections:[{id:'experience',type:'experience',title:'Experience',visible:true,order:0,entries:[{id:'exp-1',title:'Lead Product Engineer',subtitle:'Northstar Studio',period:'2022 — Now',location:'Vienna · Hybrid',body:'Led small cross-functional teams from discovery to launch, building accessible product systems used by thousands of people.',tags:['Product strategy','React','TypeScript','Design systems']},{id:'exp-2',title:'Senior Frontend Engineer',subtitle:'Fieldwork Labs',period:'2019 — 2022',location:'Berlin · Remote',body:'Created a shared interaction language across three products and introduced an evidence-driven accessibility practice.'}]},{id:'projects',type:'projects',title:'Selected work',visible:true,order:1,entries:[{id:'project-1',title:'Pulse',subtitle:'A humane operations console',body:'Reframed a noisy monitoring workflow into a focused decision surface, reducing incident triage time by 34%.',tags:['Research','Systems design','React'],url:'https://example.com'},{id:'project-2',title:'Common Ground',subtitle:'Local climate action platform',body:'Designed and built lightweight tools that help neighborhood groups turn intent into coordinated action.',tags:['Open source','Maps','Progressive web app']}]},{id:'skills',type:'skills',title:'Capabilities',visible:true,order:2,entries:[{id:'skill-1',title:'Shape',body:'Product discovery, information architecture, prototyping, technical strategy.'},{id:'skill-2',title:'Build',body:'TypeScript, React, Node.js, APIs, PostgreSQL, testing, delivery systems.'},{id:'skill-3',title:'Refine',body:'Design systems, accessibility, performance, interaction and content design.'},{id:'skill-4',title:'Lead',body:'Mentoring, facilitation, roadmap definition, cross-functional alignment.'}]},{id:'education',type:'education',title:'Education',visible:true,order:3,entries:[{id:'edu-1',title:'MSc Human–Computer Interaction',subtitle:'TU Wien',period:'2017 — 2019'},{id:'lang-1',title:'Languages',body:'German — native · English — fluent · French — conversational'}]}] };

